# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
    - post_blocks
  label: "Svg icon group"
  description: A group of svg icons with optional links
  icon: filter_vintage
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  icons: [bookshop:generic/svg-icon]
  gap: 25

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  icons:
    - bookshop:generic/svg-icon
    - bookshop:generic/svg-icon
    - bookshop:generic/svg-icon

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  gap:
    comment: Measured in pixels
    type: range
    options:
      step: 1
      max: 50
      min: 10
