# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Heading"
  description: A configurable generic heading
  icon: title
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading_text: "Hello World!"
  heading_hierarchy:
  heading_style:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  heading_text: "Hello World!"
  heading_hierarchy: h2
  heading_style: h2

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  heading_hierarchy:
    comment: There should only be one H1 element per page
    type: select
    options:
      values:
        - h1
        - h2
        - h3
        - h4
        - h5
        - h6
        - none
  heading_style:
    type: select
    options:
      values:
        - h1
        - h2
        - h3
        - h4
        - h5
        - h6