# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Background-video"
  description:
  icon: ondemand_video
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  video_id: 
  fall_back_image:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  fall_back_image: "https://placedog.net/500"

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
