# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Breadcrumbs"
  description: Breadcrumb structure of the current page within the site, can e sticky to the top of the page
  icon: keyboard_arrow_right
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  sticky: true
  

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
