# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: Footer
  description: "A footer with a navigation, further information and a newsletter form."
  icon: add_link
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text: "Hello World"
  navigation: bookshop:structures/footer/footer-navigation
  information: bookshop:structures/footer/further-information
  form: bookshop:simple/navigation-form

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  text: "Hello World"
  navigation: bookshop:structures/footer/footer-navigation
  information: bookshop:structures/footer/further-information
  form: bookshop:simple/navigation-form
  

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
